# [source.crates-io]
# registry = "git://github.com/rust-lang/crates.io-index.git"


# [target.aarch64-apple-darwin]
# rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/zld"]
#[target.aarch64-apple-darwin]
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[alias]
td = "test -- --nocapture"
tn = "nextest run"
tc = "llvm-cov nextest"
