[[bindings]]
key = "Enter"
modifiers = ["Option"]
command = "open -n /Applications/Ghostty.app"
[[bindings]]
key = "e"
modifiers = ["CMD"]
command = "open -n /Applications/Safari.app"


[[bindings]]
arrow = "Right"
modifiers = ["Ctrl"]
command = "yabai -m space --focus next"

[[bindings]]
arrow = "Left"
modifiers = ["Ctrl"]
command = "yabai -m space --focus prev"

[[bindings]]
key = "l"
modifiers = ["Ctrl", "Option"]
command = "yabai -m space --focus next"

[[bindings]]
key = "h"
modifiers = ["Ctrl", "Option"]
command = "yabai -m space --focus prev"
